# Generated by Django 5.0.3 on 2025-02-20 16:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoprograma',
            name='nombre',
        ),
        migrations.AddField(
            model_name='tipoprograma',
            name='tipo_programa',
            field=models.CharField(choices=[('Tecnico', 'Tecnico'), ('Tecnologo', 'Tecnologo')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichas',
            name='lider_ficha',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuarios'),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='tipo_programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fichas.tipoprograma'),
        ),
    ]
