# Generated by Django 5.0.3 on 2025-02-24 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_alter_fichas_lider_ficha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichas',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
