# Generated by Django 5.0.3 on 2025-02-24 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roles',
            options={},
        ),
        migrations.RemoveField(
            model_name='roles',
            name='nombre',
        ),
        migrations.AddField(
            model_name='roles',
            name='tipo_rol',
            field=models.CharField(choices=[('Instructor', 'Instructor'), ('Aprendiz', 'Aprendiz'), ('Admin', 'Admin')], default='Aprendiz', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='tipo_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.tipodoc'),
        ),
    ]
